-- Draft migration generated by generate-registration.ts at 2025-04-20T07:30:09.335Z
-- Please review and adjust column types, constraints, and defaults before applying.

BEGIN;

-- Ensure the registrations table exists (adjust if needed)
-- CREATE TABLE IF NOT EXISTS public.registrations (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
--   created_at TIMESTAMPTZ DEFAULT now(),
--   updated_at TIMESTAMPTZ DEFAULT now()
--   -- Add other base columns as needed
-- );

-- Add columns based on registrationSchema
ALTER TABLE public.registrations
  ADD COLUMN IF NOT EXISTS "email" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "full_name" TEXT,
  ADD COLUMN IF NOT EXISTS "pronouns" TEXT,
  ADD COLUMN IF NOT EXISTS "student_id" TEXT,
  ADD COLUMN IF NOT EXISTS "university" TEXT,
  ADD COLUMN IF NOT EXISTS "academic_year" TEXT,
  ADD COLUMN IF NOT EXISTS "program" TEXT,
  ADD COLUMN IF NOT EXISTS "philosophy_coursework" TEXT,
  ADD COLUMN IF NOT EXISTS "philosophy_interests" TEXT,
  ADD COLUMN IF NOT EXISTS "event_expectations" TEXT,
  ADD COLUMN IF NOT EXISTS "attendance_preference" TEXT,
  ADD COLUMN IF NOT EXISTS "workshop_preference" TEXT,
  ADD COLUMN IF NOT EXISTS "dietary_restrictions" TEXT,
  ADD COLUMN IF NOT EXISTS "accessibility_needs" TEXT,
  ADD COLUMN IF NOT EXISTS "code_of_conduct_agreement" BOOLEAN,
  ADD COLUMN IF NOT EXISTS "photo_consent" BOOLEAN,
  ADD COLUMN IF NOT EXISTS "data_privacy_consent" BOOLEAN;

-- Add/Update foreign key constraint to link registrations to users (if not already present)
ALTER TABLE public.registrations
  ADD COLUMN IF NOT EXISTS user_id UUID,
  ADD CONSTRAINT registrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- Optional: Index on user_id
CREATE INDEX IF NOT EXISTS idx_registrations_user_id ON public.registrations(user_id);

COMMIT;
